### PR TITLE
Backport ProviHealth to 1.19.2 [do not merge directly]

### PR DESCRIPTION
**Pull request by harrynull**
Attempt to backport ProviHealth to 1.19.2. Note do not merge it directly: GitHub require PRs to target an existing branch so I had to select the 1.20 branch as the base. But if you are willing to accept this. you could make a new branch and rebase this PR before merging.

I'm pretty new to Fabric so let me know if you notice something wrong. Thanks!

The other half for backporting lilylib is at Provismet/LilyLib#1.

Btw this mod looks really great! Thanks for making it.

image

### CODE REVIEW

**Comment by Provismet** [comment]
This is pretty great. I've merged the PR and cleaned up some unused imports. The LilyLib PR has also been merged, so the build workflow now functions for 1.19.2.

This isn't in an ideal state as of yet though. I've fixed the visual error with the healthbars appearing translucent, but damage particles are behaving weirdly.  
- The text isn't bound to the particle, it's most noticable at a distance. I don't know *why* this is happening given that all the matrices are the same between versions.
  - This isn't gamebreaking or anything, just somewhat annoying.
- Text appears through walls and entities.
  - This *is* fairly gamebreaking. It essentially means anything with changing health can be seen through blocks.

I couldn't figure out the cause for either of those two problems, but if you don't mind resolving them (or even just the latter one). I'll gladly make the 1.19.2 backport available to the public.

**Comment by harrynull** [comment]
Thanks! I will try to take a look

**Comment by harrynull** [comment]
I did some digging and it appears that depth test would work properly if I have Sodium+Iris installed (with no shaderpack enabled). It could be a bug with Minecraft that Iris has patched, or something else. While it would be ideal to figure out what exactly caused it, requiring users to install Iris as a workaround doesn't seem to be too unreasonable, as Iris is in pretty much every modpack.

**Comment by Provismet** [comment]
That's a great find. I tested it on my end and it works. So I've added Sodium and Iris to the required dependencies.  
I'll upload this build soon. Thanks for all the help.

**Pull request merged**
